Feature/commands
bot-schmiede/SalesBot pull request #12
Opened 2019-06-27 20:55 UTC by KillaMelone01

2019-06-27 23:36 UTC, mjkatgithub requested changes

2019-06-27 23:36 UTC, mjkatgithub commented on sales.txt
> +   link: 'http://foo.bar.baz',
remove this file

2019-06-27 23:36 UTC, mjkatgithub commented on bot.js
> +bot.on("message",function(message) {
let's use Arrow functions
```suggestion
bot.on("message", message => {
```

2019-06-27 23:36 UTC, mjkatgithub commented on bot.js
> +  console.log(message.content);// gives you a output , what is writen in the Chat
pls don't log all messages

2019-06-27 23:36 UTC, mjkatgithub commented on bot.js
> +  var args = message.content.substring(PREFIX.length).split(" ");
let's use: let
https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var#11444416

2019-06-27 23:36 UTC, mjkatgithub commented on bot.js
> +    case "testembed"://just for testing purpose(sends embed)
remove testembed case
testing is done

2019-06-27 23:36 UTC, mjkatgithub commented on bot.js
>          end: Date("now"),
use SaleEnd

2019-06-27 23:36 UTC, mjkatgithub commented on controllers/sales.js
> +function sendSale(item, index) {
remove this function

2019-06-27 23:36 UTC, mjkatgithub commented on bot.js
> +    case "day":
remove day case

2019-06-28 10:10 UTC, NYC00kie commented on sales.txt
> +   link: 'http://foo.bar.baz',
done

2019-06-28 10:11 UTC, NYC00kie commented on bot.js
> +bot.on("message",function(message) {
done

2019-06-28 10:11 UTC, NYC00kie commented on bot.js
> +  var args = message.content.substring(PREFIX.length).split(" ");
done

2019-06-28 10:11 UTC, NYC00kie commented on bot.js
> +    case "testembed"://just for testing purpose(sends embed)
done

2019-06-28 16:36 UTC, merged